sudo: false
language: python
python:
  - "3.7"
before_install:
  - pip install cython>=0.29.13
before_script:
  - pip install tox-travis
  - pip install coveralls
# command to run tests
script: tox
after_success: coveralls
